### ISSUE TITLE
Delete previously shared gameclips and/or screenshots

### ISSUE THREAD

**Issue by CptCRoche** [XboxReplay/slack-bot#1]
Hello Alexis,

Thank you for your great slack-bot. I use it on a daily basis with my colleagues to avoid working.

However, sometimes I would like to delete the previously shared gameclips and/or screenshots to avoid cluttering my conversations. Would you be able to implement this kind of feature? 

I remain at your disposal for any comments and/or questions you may have,

Best

Cpt. CRoche

**Comment by Alexis-Bize** [comment]
Hey @CptCRoche! Sure thing!
I'll try to do it once I've updated the xboxlive-api module to return missing recorded contents :) 

Thank you!

**Comment by Alexis-Bize** [comment]
Unfortunately this can not be done, sorry 😶
